workflows:
  flutter-debug-build:
    name: Flutter Debug Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      vars:
        PROJECT_NAME: "RecipeShopper"

    scripts:
      - name: Clone repository
        script: git clone $CM_REPO $CM_BUILD_DIR

      - name: Set up Flutter
        script: flutter doctor

      - name: Install dependencies
        script: flutter pub get

      - name: Build Android Debug APK
        script: flutter build apk --debug \
          --dart-define=PROJECT_ID=$PROJECT_ID \
          --dart-define=DB_ID=$DB_ID \
          --dart-define=RECIPE_COLLECTION_ID=$RECIPE_COLLECTION_ID \
          --dart-define=INGREDIENTS_COLLECTION_ID=$INGREDIENTS_COLLECTION_ID \
          --dart-define=RECIPE_IMAGES_BUCKET_ID=$RECIPE_IMAGES_BUCKET_ID

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

    publishing:
      email:
        recipients:
          - "justmax7cb@gmail.com"
